((identifier) @function)
((binding) @operator)
((string_literal) @string)
((localization_marker) @punctuation.special)
((list_marker) @punctuation.special)
((dict_marker) @punctuation.special)

((component_name) @function)
((property_name) @property)
((parameter) @parameter)
((parameter_marker) @punctuation.special)
((primitive_literal) @constant)
((null_value) @constant)
((component_declaration) @keyword)
((component_declaration (identifier)) @type)
((property) @property)
((indent) @punctuation)

((identifier) @variable)
((component) @type)
((node) @scope)
