/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 46
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_indent = 1,
  sym_css_variable = 2,
  sym_identifier = 3,
  anon_sym_DOLLAR = 4,
  sym_parameter_marker = 5,
  anon_sym_BSLASH = 6,
  aux_sym_string_literal_token1 = 7,
  anon_sym_true = 8,
  anon_sym_false = 9,
  anon_sym_null = 10,
  aux_sym_primitive_literal_token1 = 11,
  sym_list_marker = 12,
  sym_dict_marker = 13,
  sym_null_value = 14,
  anon_sym_LT_EQ = 15,
  anon_sym_EQ_GT = 16,
  anon_sym_LT_EQ_GT = 17,
  sym_localization_marker = 18,
  anon_sym_SPACE = 19,
  sym_caret = 20,
  sym_source_file = 21,
  sym_component = 22,
  sym_component_name = 23,
  sym_property_name = 24,
  sym_parameter = 25,
  sym_string_literal = 26,
  sym_primitive_literal = 27,
  sym_binding = 28,
  sym_component_binding = 29,
  sym_component_declaration_with_inline = 30,
  sym_component_declaration = 31,
  sym_property = 32,
  sym_node = 33,
  aux_sym_source_file_repeat1 = 34,
  aux_sym_component_repeat1 = 35,
  aux_sym_component_declaration_repeat1 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_indent] = "indent",
  [sym_css_variable] = "css_variable",
  [sym_identifier] = "identifier",
  [anon_sym_DOLLAR] = "$",
  [sym_parameter_marker] = "parameter_marker",
  [anon_sym_BSLASH] = "\\",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_null] = "null",
  [aux_sym_primitive_literal_token1] = "primitive_literal_token1",
  [sym_list_marker] = "list_marker",
  [sym_dict_marker] = "dict_marker",
  [sym_null_value] = "null_value",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_LT_EQ_GT] = "<=>",
  [sym_localization_marker] = "localization_marker",
  [anon_sym_SPACE] = " ",
  [sym_caret] = "caret",
  [sym_source_file] = "source_file",
  [sym_component] = "component",
  [sym_component_name] = "component_name",
  [sym_property_name] = "property_name",
  [sym_parameter] = "parameter",
  [sym_string_literal] = "string_literal",
  [sym_primitive_literal] = "primitive_literal",
  [sym_binding] = "binding",
  [sym_component_binding] = "component_binding",
  [sym_component_declaration_with_inline] = "component_declaration_with_inline",
  [sym_component_declaration] = "component_declaration",
  [sym_property] = "property",
  [sym_node] = "node",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_component_repeat1] = "component_repeat1",
  [aux_sym_component_declaration_repeat1] = "component_declaration_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_indent] = sym_indent,
  [sym_css_variable] = sym_css_variable,
  [sym_identifier] = sym_identifier,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_parameter_marker] = sym_parameter_marker,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_null] = anon_sym_null,
  [aux_sym_primitive_literal_token1] = aux_sym_primitive_literal_token1,
  [sym_list_marker] = sym_list_marker,
  [sym_dict_marker] = sym_dict_marker,
  [sym_null_value] = sym_null_value,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_LT_EQ_GT] = anon_sym_LT_EQ_GT,
  [sym_localization_marker] = sym_localization_marker,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [sym_caret] = sym_caret,
  [sym_source_file] = sym_source_file,
  [sym_component] = sym_component,
  [sym_component_name] = sym_component_name,
  [sym_property_name] = sym_property_name,
  [sym_parameter] = sym_parameter,
  [sym_string_literal] = sym_string_literal,
  [sym_primitive_literal] = sym_primitive_literal,
  [sym_binding] = sym_binding,
  [sym_component_binding] = sym_component_binding,
  [sym_component_declaration_with_inline] = sym_component_declaration_with_inline,
  [sym_component_declaration] = sym_component_declaration,
  [sym_property] = sym_property,
  [sym_node] = sym_node,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_component_repeat1] = aux_sym_component_repeat1,
  [aux_sym_component_declaration_repeat1] = aux_sym_component_declaration_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_indent] = {
    .visible = true,
    .named = true,
  },
  [sym_css_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_parameter_marker] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_primitive_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_list_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_dict_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_null_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_localization_marker] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [sym_caret] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_component] = {
    .visible = true,
    .named = true,
  },
  [sym_component_name] = {
    .visible = true,
    .named = true,
  },
  [sym_property_name] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_component_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_component_declaration_with_inline] = {
    .visible = true,
    .named = true,
  },
  [sym_component_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_node] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_component_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_component_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 27,
  [34] = 26,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 43,
  [45] = 42,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '$', 40,
        '*', 54,
        '-', 56,
        '/', 53,
        '<', 4,
        '=', 6,
        '@', 61,
        '\\', 42,
        '^', 63,
        'f', 28,
        'n', 37,
        't', 34,
        '!', 41,
        '?', 41,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 1:
      if (lookahead == '$') ADVANCE(40);
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '\\') ADVANCE(42);
      if (lookahead == 'f') ADVANCE(28);
      if (lookahead == 'n') ADVANCE(37);
      if (lookahead == 't') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(55);
      if (lookahead == '<') ADVANCE(5);
      if (lookahead == '\\') ADVANCE(42);
      if (lookahead == '^') ADVANCE(63);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(58);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(57);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(59);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(49);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 15:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 16:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 18:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 19:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '\t', 25,
        '$', 40,
        '*', 54,
        '-', 2,
        '/', 53,
        '<', 4,
        '=', 6,
        '@', 61,
        '\\', 42,
        'f', 28,
        'n', 37,
        't', 34,
      );
      if (('\n' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 20:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '\t', 25,
        '$', 39,
        '*', 54,
        '-', 2,
        '/', 53,
        '<', 4,
        '=', 6,
        '@', 61,
        '\\', 42,
        'f', 7,
        'n', 16,
        't', 13,
        '!', 41,
        '?', 41,
      );
      if (('\n' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 21:
      if (eof) ADVANCE(24);
      if (lookahead == '\t') ADVANCE(26);
      if (lookahead == ' ') ADVANCE(62);
      if (lookahead == '$') ADVANCE(40);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 22:
      if (eof) ADVANCE(24);
      if (lookahead == '\t') ADVANCE(26);
      if (lookahead == ' ') ADVANCE(62);
      if (lookahead == '$') ADVANCE(39);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(22);
      END_STATE();
    case 23:
      if (eof) ADVANCE(24);
      if (lookahead == '$') ADVANCE(39);
      if (lookahead == '\\') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_indent);
      if (lookahead == '\t') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_indent);
      if (lookahead == '\t') ADVANCE(26);
      if (lookahead == ' ') ADVANCE(62);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_css_variable);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(31);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(46);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(48);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(35);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(50);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(32);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(36);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(30);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(29);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(33);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_parameter_marker);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_null);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_primitive_literal_token1);
      if (lookahead == '.') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_primitive_literal_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_list_marker);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_dict_marker);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_null_value);
      if (lookahead == '-') ADVANCE(18);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_null_value);
      if (lookahead == '-') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      if (lookahead == '>') ADVANCE(60);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_LT_EQ_GT);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_localization_marker);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == '\t') ADVANCE(26);
      if (lookahead == ' ') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_caret);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 23},
  [2] = {.lex_state = 20},
  [3] = {.lex_state = 20},
  [4] = {.lex_state = 20},
  [5] = {.lex_state = 19},
  [6] = {.lex_state = 20},
  [7] = {.lex_state = 20},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 20},
  [12] = {.lex_state = 20},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 21},
  [15] = {.lex_state = 21},
  [16] = {.lex_state = 21},
  [17] = {.lex_state = 23},
  [18] = {.lex_state = 20},
  [19] = {.lex_state = 20},
  [20] = {.lex_state = 20},
  [21] = {.lex_state = 20},
  [22] = {.lex_state = 23},
  [23] = {.lex_state = 20},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 21},
  [26] = {.lex_state = 21},
  [27] = {.lex_state = 21},
  [28] = {.lex_state = 23},
  [29] = {.lex_state = 22},
  [30] = {.lex_state = 20},
  [31] = {.lex_state = 20},
  [32] = {.lex_state = 20},
  [33] = {.lex_state = 20},
  [34] = {.lex_state = 20},
  [35] = {.lex_state = 20},
  [36] = {.lex_state = 20},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 20},
  [39] = {.lex_state = 23},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 43},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 43},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_css_variable] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym_parameter_marker] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [aux_sym_primitive_literal_token1] = ACTIONS(1),
    [sym_list_marker] = ACTIONS(1),
    [sym_dict_marker] = ACTIONS(1),
    [sym_null_value] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_LT_EQ_GT] = ACTIONS(1),
    [sym_localization_marker] = ACTIONS(1),
    [sym_caret] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(40),
    [sym_component] = STATE(17),
    [sym_component_name] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_DOLLAR] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    STATE(9), 1,
      sym_binding,
    ACTIONS(7), 2,
      ts_builtin_sym_end,
      sym_indent,
    STATE(38), 2,
      sym_string_literal,
      sym_primitive_literal,
    ACTIONS(17), 3,
      anon_sym_LT_EQ,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
    ACTIONS(9), 4,
      sym_css_variable,
      sym_list_marker,
      sym_dict_marker,
      sym_localization_marker,
    ACTIONS(15), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
      aux_sym_primitive_literal_token1,
  [35] = 8,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    STATE(8), 1,
      sym_binding,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      sym_indent,
    STATE(32), 2,
      sym_string_literal,
      sym_primitive_literal,
    ACTIONS(17), 3,
      anon_sym_LT_EQ,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
    ACTIONS(15), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
      aux_sym_primitive_literal_token1,
    ACTIONS(21), 4,
      sym_css_variable,
      sym_list_marker,
      sym_dict_marker,
      sym_localization_marker,
  [70] = 4,
    ACTIONS(29), 1,
      sym_parameter_marker,
    STATE(6), 1,
      sym_parameter,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      sym_indent,
    ACTIONS(27), 13,
      sym_css_variable,
      anon_sym_DOLLAR,
      anon_sym_BSLASH,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
      aux_sym_primitive_literal_token1,
      sym_list_marker,
      sym_dict_marker,
      anon_sym_LT_EQ,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
      sym_localization_marker,
  [96] = 3,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(31), 2,
      ts_builtin_sym_end,
      sym_indent,
    ACTIONS(33), 13,
      sym_css_variable,
      anon_sym_DOLLAR,
      anon_sym_BSLASH,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
      aux_sym_primitive_literal_token1,
      sym_list_marker,
      sym_dict_marker,
      anon_sym_LT_EQ,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
      sym_localization_marker,
  [119] = 2,
    ACTIONS(37), 2,
      ts_builtin_sym_end,
      sym_indent,
    ACTIONS(39), 13,
      sym_css_variable,
      anon_sym_DOLLAR,
      anon_sym_BSLASH,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
      aux_sym_primitive_literal_token1,
      sym_list_marker,
      sym_dict_marker,
      anon_sym_LT_EQ,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
      sym_localization_marker,
  [139] = 2,
    ACTIONS(41), 2,
      ts_builtin_sym_end,
      sym_indent,
    ACTIONS(43), 13,
      sym_css_variable,
      anon_sym_DOLLAR,
      anon_sym_BSLASH,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
      aux_sym_primitive_literal_token1,
      sym_list_marker,
      sym_dict_marker,
      anon_sym_LT_EQ,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
      sym_localization_marker,
  [159] = 8,
    ACTIONS(45), 1,
      sym_css_variable,
    ACTIONS(47), 1,
      sym_identifier,
    ACTIONS(49), 1,
      anon_sym_DOLLAR,
    ACTIONS(51), 1,
      anon_sym_BSLASH,
    ACTIONS(53), 1,
      aux_sym_primitive_literal_token1,
    STATE(11), 1,
      sym_property_name,
    ACTIONS(15), 3,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
    STATE(36), 3,
      sym_component_name,
      sym_string_literal,
      sym_primitive_literal,
  [188] = 8,
    ACTIONS(45), 1,
      sym_css_variable,
    ACTIONS(47), 1,
      sym_identifier,
    ACTIONS(49), 1,
      anon_sym_DOLLAR,
    ACTIONS(51), 1,
      anon_sym_BSLASH,
    ACTIONS(53), 1,
      aux_sym_primitive_literal_token1,
    STATE(12), 1,
      sym_property_name,
    ACTIONS(15), 3,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
    STATE(32), 3,
      sym_component_name,
      sym_string_literal,
      sym_primitive_literal,
  [217] = 8,
    ACTIONS(51), 1,
      anon_sym_BSLASH,
    ACTIONS(55), 1,
      sym_null_value,
    ACTIONS(57), 1,
      anon_sym_LT_EQ,
    ACTIONS(59), 1,
      sym_caret,
    STATE(2), 1,
      sym_property_name,
    STATE(29), 1,
      sym_component_declaration,
    ACTIONS(45), 2,
      sym_css_variable,
      sym_identifier,
    STATE(19), 3,
      sym_string_literal,
      sym_component_declaration_with_inline,
      sym_property,
  [245] = 5,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    ACTIONS(63), 1,
      anon_sym_DOLLAR,
    ACTIONS(61), 2,
      ts_builtin_sym_end,
      sym_indent,
    STATE(30), 2,
      sym_string_literal,
      sym_primitive_literal,
    ACTIONS(15), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
      aux_sym_primitive_literal_token1,
  [266] = 5,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    ACTIONS(67), 1,
      anon_sym_DOLLAR,
    ACTIONS(65), 2,
      ts_builtin_sym_end,
      sym_indent,
    STATE(36), 2,
      sym_string_literal,
      sym_primitive_literal,
    ACTIONS(15), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
      aux_sym_primitive_literal_token1,
  [287] = 2,
    ACTIONS(69), 3,
      sym_css_variable,
      anon_sym_BSLASH,
      aux_sym_primitive_literal_token1,
    ACTIONS(71), 5,
      sym_identifier,
      anon_sym_DOLLAR,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
  [300] = 4,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 1,
      sym_identifier,
    STATE(15), 2,
      sym_component_binding,
      aux_sym_component_declaration_repeat1,
    ACTIONS(75), 3,
      sym_indent,
      anon_sym_DOLLAR,
      anon_sym_SPACE,
  [316] = 4,
    ACTIONS(77), 1,
      sym_identifier,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    STATE(16), 2,
      sym_component_binding,
      aux_sym_component_declaration_repeat1,
    ACTIONS(81), 3,
      sym_indent,
      anon_sym_DOLLAR,
      anon_sym_SPACE,
  [332] = 4,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(87), 1,
      sym_identifier,
    STATE(16), 2,
      sym_component_binding,
      aux_sym_component_declaration_repeat1,
    ACTIONS(85), 3,
      sym_indent,
      anon_sym_DOLLAR,
      anon_sym_SPACE,
  [348] = 4,
    ACTIONS(5), 1,
      anon_sym_DOLLAR,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
    STATE(21), 1,
      sym_component_name,
    STATE(22), 2,
      sym_component,
      aux_sym_source_file_repeat1,
  [362] = 4,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    ACTIONS(94), 1,
      sym_indent,
    ACTIONS(96), 1,
      anon_sym_DOLLAR,
    STATE(20), 2,
      sym_node,
      aux_sym_component_repeat1,
  [376] = 4,
    ACTIONS(94), 1,
      sym_indent,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
    ACTIONS(100), 1,
      anon_sym_DOLLAR,
    STATE(23), 2,
      sym_node,
      aux_sym_component_repeat1,
  [390] = 4,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
    ACTIONS(104), 1,
      sym_indent,
    ACTIONS(107), 1,
      anon_sym_DOLLAR,
    STATE(20), 2,
      sym_node,
      aux_sym_component_repeat1,
  [404] = 4,
    ACTIONS(94), 1,
      sym_indent,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    ACTIONS(111), 1,
      anon_sym_DOLLAR,
    STATE(18), 2,
      sym_node,
      aux_sym_component_repeat1,
  [418] = 4,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    ACTIONS(115), 1,
      anon_sym_DOLLAR,
    STATE(21), 1,
      sym_component_name,
    STATE(22), 2,
      sym_component,
      aux_sym_source_file_repeat1,
  [432] = 4,
    ACTIONS(94), 1,
      sym_indent,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 1,
      anon_sym_DOLLAR,
    STATE(20), 2,
      sym_node,
      aux_sym_component_repeat1,
  [446] = 4,
    ACTIONS(59), 1,
      sym_caret,
    STATE(2), 1,
      sym_property_name,
    STATE(35), 1,
      sym_property,
    ACTIONS(45), 2,
      sym_css_variable,
      sym_identifier,
  [460] = 2,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
    ACTIONS(124), 4,
      sym_indent,
      sym_identifier,
      anon_sym_DOLLAR,
      anon_sym_SPACE,
  [470] = 2,
    ACTIONS(126), 1,
      ts_builtin_sym_end,
    ACTIONS(128), 4,
      sym_indent,
      sym_identifier,
      anon_sym_DOLLAR,
      anon_sym_SPACE,
  [480] = 2,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
    ACTIONS(132), 4,
      sym_indent,
      sym_identifier,
      anon_sym_DOLLAR,
      anon_sym_SPACE,
  [490] = 3,
    ACTIONS(134), 1,
      anon_sym_DOLLAR,
    ACTIONS(136), 1,
      anon_sym_BSLASH,
    STATE(25), 2,
      sym_component_name,
      sym_string_literal,
  [501] = 3,
    ACTIONS(138), 1,
      ts_builtin_sym_end,
    ACTIONS(142), 1,
      anon_sym_SPACE,
    ACTIONS(140), 2,
      sym_indent,
      anon_sym_DOLLAR,
  [512] = 2,
    ACTIONS(146), 1,
      anon_sym_DOLLAR,
    ACTIONS(144), 2,
      ts_builtin_sym_end,
      sym_indent,
  [520] = 2,
    ACTIONS(150), 1,
      anon_sym_DOLLAR,
    ACTIONS(148), 2,
      ts_builtin_sym_end,
      sym_indent,
  [528] = 2,
    ACTIONS(67), 1,
      anon_sym_DOLLAR,
    ACTIONS(65), 2,
      ts_builtin_sym_end,
      sym_indent,
  [536] = 2,
    ACTIONS(132), 1,
      anon_sym_DOLLAR,
    ACTIONS(130), 2,
      ts_builtin_sym_end,
      sym_indent,
  [544] = 2,
    ACTIONS(128), 1,
      anon_sym_DOLLAR,
    ACTIONS(126), 2,
      ts_builtin_sym_end,
      sym_indent,
  [552] = 2,
    ACTIONS(154), 1,
      anon_sym_DOLLAR,
    ACTIONS(152), 2,
      ts_builtin_sym_end,
      sym_indent,
  [560] = 2,
    ACTIONS(63), 1,
      anon_sym_DOLLAR,
    ACTIONS(61), 2,
      ts_builtin_sym_end,
      sym_indent,
  [568] = 2,
    STATE(3), 1,
      sym_property_name,
    ACTIONS(45), 2,
      sym_css_variable,
      sym_identifier,
  [576] = 2,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      sym_indent,
  [584] = 2,
    ACTIONS(134), 1,
      anon_sym_DOLLAR,
    STATE(14), 1,
      sym_component_name,
  [591] = 1,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
  [595] = 1,
    ACTIONS(158), 1,
      sym_identifier,
  [599] = 1,
    ACTIONS(160), 1,
      aux_sym_string_literal_token1,
  [603] = 1,
    ACTIONS(162), 1,
      sym_identifier,
  [607] = 1,
    ACTIONS(164), 1,
      sym_identifier,
  [611] = 1,
    ACTIONS(166), 1,
      aux_sym_string_literal_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 70,
  [SMALL_STATE(5)] = 96,
  [SMALL_STATE(6)] = 119,
  [SMALL_STATE(7)] = 139,
  [SMALL_STATE(8)] = 159,
  [SMALL_STATE(9)] = 188,
  [SMALL_STATE(10)] = 217,
  [SMALL_STATE(11)] = 245,
  [SMALL_STATE(12)] = 266,
  [SMALL_STATE(13)] = 287,
  [SMALL_STATE(14)] = 300,
  [SMALL_STATE(15)] = 316,
  [SMALL_STATE(16)] = 332,
  [SMALL_STATE(17)] = 348,
  [SMALL_STATE(18)] = 362,
  [SMALL_STATE(19)] = 376,
  [SMALL_STATE(20)] = 390,
  [SMALL_STATE(21)] = 404,
  [SMALL_STATE(22)] = 418,
  [SMALL_STATE(23)] = 432,
  [SMALL_STATE(24)] = 446,
  [SMALL_STATE(25)] = 460,
  [SMALL_STATE(26)] = 470,
  [SMALL_STATE(27)] = 480,
  [SMALL_STATE(28)] = 490,
  [SMALL_STATE(29)] = 501,
  [SMALL_STATE(30)] = 512,
  [SMALL_STATE(31)] = 520,
  [SMALL_STATE(32)] = 528,
  [SMALL_STATE(33)] = 536,
  [SMALL_STATE(34)] = 544,
  [SMALL_STATE(35)] = 552,
  [SMALL_STATE(36)] = 560,
  [SMALL_STATE(37)] = 568,
  [SMALL_STATE(38)] = 576,
  [SMALL_STATE(39)] = 584,
  [SMALL_STATE(40)] = 591,
  [SMALL_STATE(41)] = 595,
  [SMALL_STATE(42)] = 599,
  [SMALL_STATE(43)] = 603,
  [SMALL_STATE(44)] = 607,
  [SMALL_STATE(45)] = 611,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_name, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_name, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_name, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_name, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 4, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 4, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binding, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_declaration, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component_declaration, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_declaration, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component_declaration, 4, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_component_declaration_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_component_declaration_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_component_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_binding, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component_binding, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_name, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component_name, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_declaration_with_inline, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component_declaration_with_inline, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 5, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 5, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_literal, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primitive_literal, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_declaration_with_inline, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component_declaration_with_inline, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_molviewtree(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "molviewtree",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
